---
- hosts: all
  vars_files:
    - group_vars/all/vault
  tasks:
#    - name: Print
#      ansible.builtin.debug:
#        var: release_name.stdout

    - name: Install required packages
      become: yes
      apt:
        update_cache: yes
        name:
          - git
          - net-tools
          - python3-dev
          - python3-pip
          - python3-venv
          - apt-transport-https
          - ca-certificates
          - curl
          - lsb-release
        state: present

    - name: Add Docker GPG apt Key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Get current OS release name
      ansible.builtin.shell: lsb_release -cs
      register: release_name
      changed_when: no

    - name: Add Docker Repository
      become: true
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ release_name.stdout }} stable
        state: present

    - name: Install Docker packages
      become: yes
      apt:
        update_cache: yes
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
        state: present

    - name: Add user {{ user }} to a group of 'docker'
      become: yes
      ansible.builtin.user:
        name: '{{ user }}'
        group: docker

    - name: Create Findus project folder
      ansible.builtin.file:
        path: ~/findus
        state: directory
        mode: '0764'

    - name: Clone DCN repository
      ansible.builtin.git:
        repo: https://github.com/VadimKovalchuk/DCN.git
        dest: ~/findus/dcn
        version: develop

    - name: Clone findus-core repository
      ansible.builtin.git:
        repo: https://github.com/VadimKovalchuk/findus-core.git
        dest: ~/findus/core
        version: develop

    - name: Clone findus-edge repository
      ansible.builtin.git:
        repo: https://github.com/VadimKovalchuk/findus-edge.git
        dest: ~/findus/edge
        version: main

    - name: Initiate virtualenv for findus-edge
      pip:
        virtualenv: ~/findus/venv/edge
        virtualenv_command: python3 -m venv
        requirements: ~/findus/edge/requirements.txt

    - name: Initiate virtualenv for DCN
      pip:
        virtualenv: ~/findus/venv/dcn
        virtualenv_command: python3 -m venv
        requirements: ~/findus/dcn/requirements.txt

    - name: Initiate virtualenv for findus-core
      pip:
        virtualenv: ~/findus/venv/core
        virtualenv_command: python3 -m venv
        requirements: ~/findus/core/requirements.txt

    - name: Extend findus-core requirements with requirements from DCN
      pip:
        requirements: ~/findus/dcn/requirements.txt
        virtualenv: ~/findus/venv/core

    - name: Extend DCN requirements with requirements from findus-edge
      pip:
        requirements: ~/findus/edge/requirements.txt
        virtualenv: ~/findus/venv/dcn

#    - name: Create findus-edge folder on DCN agent modules
#      ansible.builtin.file:
#        path: ~/findus/dcn/agent/modules/findus-edge
#        state: directory
#        mode: '0644'

    - name: Embadding findus-edge into DCN agent
#      copy:
#        src: ~/findus/edge/
#        dest: ~/findus/dcn/agent/modules/findus-edge/
#        remote_src: yes
#        directory_mode: yes
#        mode: '0644'
      ansible.builtin.git:
        repo: https://github.com/VadimKovalchuk/findus-edge.git
        dest: ~/findus/dcn/agent/modules/findus-edge
        version: main

    - name: Embadding DCN common module into findus-core
      copy:
        src: ~/findus/dcn/common/
        dest: ~/findus/core/common
        remote_src: yes
        directory_mode: yes
        owner: scorcher
        mode: '0764'

    - name: Copy DCN recuirements into findus folder
      copy:
        src: ~/findus/dcn/requirements.txt
        dest: ~/findus/core/requirements-dcn.txt
        remote_src: yes
        mode: '0664'

    - name: Embadding DCN client module into findus-core
      copy:
        src: ~/findus/dcn/client/
        dest: ~/findus/core/client
        remote_src: yes
        directory_mode: yes
        owner: scorcher
        mode: '0764'

    - name: Pull Python 3.8 image
      community.docker.docker_image:
        name: python:3.8
        source: pull
        pull:
          platform: amd64

    - name: Pull Postgress DB image
      community.docker.docker_image:
        name: postgres:13
        source: pull
        pull:
          platform: amd64

    - name: Pull Adminer image
      community.docker.docker_image:
        name: adminer
        source: pull
        pull:
          platform: amd64
    
    - name: Pull RabbitMQ image
      community.docker.docker_image:
        name: rabbitmq:3.8.4-management
        source: pull
        pull:
          platform: amd64
    
    - name: Build DCN image
      community.docker.docker_image:
        name: dcn
        build:
          path: ~/findus/dcn/
        source: build
      vars:
        ansible_python_interpreter: ~/findus/venv/dcn/bin/python3
      tags: build

    - name: Build Findus image
      community.docker.docker_image:
        name: findus
        build:
          path: ~/findus/core/
        source: build
      vars:
        ansible_python_interpreter: ~/findus/venv/core/bin/python3
      tags: build