version: "3.10"
services:
  database:
    image: "postgres:15"
    restart: always
    env_file:
      - database.env
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
  adminer:
    image: "adminer"
    restart: always
    ports:
      - 8080:8080
  rabbitmq:
    image: "rabbitmq:3.11-management"
    restart: always
    deploy:
      mode: global
    ports:
      - "5672:5672"
      - "15672:15672"
  dispatcher:
    image: "dcn:latest"
    deploy:
      mode: global
    ports:
      - "9999:9999"
    command: ["python", "service/dispatcher.py", "rabbitmq"]
    volumes:
      - ./log/dispatcher/:/src/log/dispatcher/
  agent:
    image: "dcn:latest"
    command: ["python", "service/agent.py", "dispatcher", "docker"]
    volumes:
      - ./log/agent/:/src/log/agent/
    deploy:
      mode: replicated
      replicas: 1
  dcn_client:
    image: "findus:latest"
    command: ["python", "manage.py", "dcn_client"]
    volumes:
      - ./log/client/:/src/log/django/
    deploy:
      mode: global
#  task_processor:
#    image: "findus:latest"
#    command: ["python", "manage.py", "task_processor"]
#    volumes:
#      - ./log/task_processor/:/src/log/django/
#    deploy:
#      mode: global
  flow_processor:
    image: "findus:latest"
    command: ["python", "manage.py", "flow_processor"]
    volumes:
      - ./log/flow_processor/:/src/log/django/
    deploy:
      mode: global
  scheduler:
    image: "findus:latest"
    command: ["python", "manage.py", "scheduler"]
    volumes:
      - ./log/scheduler/:/src/log/django/
    deploy:
      mode: global
#  web_server:
#    image: "findus:latest"
#    command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
#    volumes:
#      - ./log/web_server/:/src/log/django/
#    deploy:
#      mode: global
#    ports:
#      - 8000:8000
