- name: Create packages folder
  ansible.builtin.file:
    path: '{{ project_path }}/dcn/packages'
    state: directory
    mode: '0764'

- name: Clone findus-edge repository to packages folder
  ansible.builtin.git:
    repo: git@github.com:VadimKovalchuk/findus-edge.git
    dest: '{{ project_path }}/dcn/packages/edge'
    version: '{{ edge_branch }}'

- name: Building wheels for Findus-edge
  ansible.builtin.shell:
  args:
    chdir: '{{ project_path }}/dcn/packages/edge'
    cmd: 'source {{ general_venv }}/dcn/bin/activate && python setup.py bdist_wheel'
    executable: /bin/bash

- name: Install findus-edge package to DCN env
  pip:
    virtualenv: '{{ general_venv }}/dcn'
    name: 'file://{{ project_path }}/dcn/packages/edge/dist/findus_edge-0.0.1-py3-none-any.whl'
