- name: Create Findus project folder
  ansible.builtin.file:
    path: '{{ project_path }}'
    state: directory
    mode: '0764'

- name: Clone DCN repository
  ansible.builtin.git:
    repo: https://github.com/VadimKovalchuk/DCN.git
    dest: '{{ project_path }}/dcn'
    version: '{{ dcn_branch }}'

- name: Clone findus-core repository
  ansible.builtin.git:
    repo: https://github.com/VadimKovalchuk/findus-core.git
    dest: '{{ core_path }}'
    version: '{{ core_branch }}'

- name: Clone findus-edge repository
  ansible.builtin.git:
    repo: https://github.com/VadimKovalchuk/findus-edge.git
    dest: '{{ project_path }}/edge'
    version: '{{ edge_branch }}'

- name: Initiate virtualenv for findus-edge
  pip:
    virtualenv: '{{ general_venv }}/edge'
    virtualenv_command: python3 -m venv
    requirements: ~/findus/edge/requirements.txt

- name: Initiate virtualenv for DCN
  pip:
    virtualenv: '{{ general_venv }}/dcn'
    virtualenv_command: python3 -m venv
    requirements: ~/findus/dcn/requirements.txt

- name: Initiate virtualenv for findus-core
  pip:
    virtualenv: ~/findus/venv/core
    virtualenv_command: python3 -m venv
    requirements: '{{ core_path }}/requirements.txt'

- name: Extend findus-core requirements with requirements from DCN
  pip:
    requirements: ~/findus/dcn/requirements.txt
    virtualenv: ~/findus/venv/core

- name: Extend DCN requirements with requirements from findus-edge
  pip:
    requirements: ~/findus/edge/requirements.txt
    virtualenv: ~/findus/venv/dcn

- name: Embadding findus-edge into DCN agent
#      copy:
#        src: ~/findus/edge/
#        dest: ~/findus/dcn/agent/modules/findus-edge/
#        remote_src: yes
#        directory_mode: yes
#        mode: '0644'
  ansible.builtin.git:
    repo: https://github.com/VadimKovalchuk/findus-edge.git
    dest: ~/findus/dcn/agent/modules/findus-edge
    version: main

- name: Embadding DCN common module into findus-core
  copy:
    src: ~/findus/dcn/common/
    dest: '{{ core_path }}/common'
    remote_src: yes
    directory_mode: yes
    owner: scorcher
    mode: '0764'

- name: Embadding DCN client module into findus-core
  copy:
    src: ~/findus/dcn/client/
    dest: '{{ core_path }}/client'
    remote_src: yes
    directory_mode: yes
    owner: scorcher
    mode: '0764'

- name: Copy DCN recuirements file into findus folder
  copy:
    src: ~/findus/dcn/requirements.txt
    dest: '{{ core_path }}/requirements-dcn.txt'
    remote_src: yes
    mode: '0664'

- name: Create debug log folder
  ansible.builtin.file:
    path: '{{ core_path }}/log'
    state: directory
    mode: '0764'

# TODO: Move to Django role
- name: Creating config file for Django settings
  template:
    src: settings.yaml
    dest: '{{ core_path }}/settings.yaml'
