- name: Create Findus project folder
  ansible.builtin.file:
    path: '{{ project_path }}'
    state: directory
    mode: '0764'

- name: Clone DCN repository
  ansible.builtin.git:
    repo: git@github.com:VadimKovalchuk/DCN.git
    dest: '{{ project_path }}/dcn'
    version: '{{ dcn_branch }}'

- name: Clone findus-core repository
  ansible.builtin.git:
    repo: git@github.com:VadimKovalchuk/findus-core.git
    dest: '{{ core_path }}'  # findus/core
    version: '{{ core_branch }}'

- name: Clone findus-edge repository
  ansible.builtin.git:
    repo: git@github.com:VadimKovalchuk/findus-edge.git
    dest: '{{ project_path }}/edge'
    version: '{{ edge_branch }}'

- name: Initiate virtualenv for findus-edge
  pip:
    virtualenv: '{{ general_venv }}/edge'
    virtualenv_command: python3 -m venv
    requirements: '{{ project_path }}/edge/requirements.txt'

- name: Initiate virtualenv for DCN
  pip:
    virtualenv: '{{ general_venv }}/dcn'
    virtualenv_command: python3 -m venv
    requirements: '{{ project_path }}/dcn/requirements.txt'

- name: Initiate virtualenv for findus-core
  pip:
    virtualenv: '{{ core_venv }}'  # findus/venv/core
    virtualenv_command: python3 -m venv
    requirements: '{{ core_path }}/requirements.txt'

- name: Create debug log folder
  ansible.builtin.file:
    path: '{{ core_path }}/log'
    state: directory
    mode: '0764'

# TODO: Move to Django role
- name: Creating config file for Django settings
  template:
    src: settings.yaml
    dest: '{{ core_path }}/settings.yaml'
