- name: Create migrations in database
  community.general.django_manage:
    command: makemigrations
    project_path: "{{ core_path }}"
    settings: "{{ core_path }}/settings"
    pythonpath: "{{ core_path }}"
    virtualenv: "{{ core_venv }}"
