- name: Install required packages
  become: yes
  apt:
    update_cache: yes
    name:
      - git
      - net-tools
      - python3-dev
      - python3-pip
      - python3-venv
      - apt-transport-https
      - ca-certificates
      - curl
      - lsb-release
    state: present

- name: Add Docker GPG apt Key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Get current OS release name
  ansible.builtin.shell: lsb_release -cs
  register: release_name
  changed_when: no

- name: Add Docker Repository
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ release_name.stdout }} stable
    state: present

- name: Install Docker packages
  become: yes
  apt:
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Add user {{ user }} to a group of 'docker'
  become: yes
  ansible.builtin.user:
    name: '{{ user }}'
    group: docker

- name: Reset ssh connection to allow user changes to affect
  ansible.builtin.meta:
    reset_connection
